version: '3'

services:
    website:
        build: .
        container_name: blockchain-v1
        # command: npm run start
        command: ["tail", "-f", "/dev/null"]
        volumes:
            - ./:/blockchain
            - /blockchain/node_modules
            - .env:/blockchain/.env
        ports:
            - "3003:3000"
        environment: 
            - NODE_ENV=${env}